version: "2.1"

networks:
  balance:
    driver: bridge

services:
  redis:
    container_name: balance-redis
    image: redis:latest
    networks:
      - balance
  balance-web:
    container_name: balance-web
    ports:
      - "3003:3003"
    command: "npm run start-balance"
    extends:
      file: ../base.yml
      service: ledger
    depends_on:
      - redis
    networks:
      - balance
