version: "2"

networks:
  ledger:
    driver: bridge

services:
  mongo:
    container_name: ledger-mongo
    image: mongo:latest
    networks:
      - ledger
  redis:
    container_name: ledger-redis
    image: redis:latest
    networks:
      - ledger
  eyeshade_worker:
    container_name: ledger-eyeshade-worker
    command: "npm run start-eyeshade-worker"
    extends:
      file: base.yml
      service: ledger
    depends_on:
      - mongo
      - redis
  eyeshade_web:
    container_name: ledger-eyeshade-web
    ports:
      - "3002:3002"
    command: "npm run start-eyeshade"
    extends:
      file: base.yml
      service: ledger
    depends_on:
      - mongo
      - redis
