version: "2"

networks:
  ledger:
    driver: bridge

services:
  mongo:
    container_name: ledger-mongo
    image: mongo:latest
    networks:
      - ledger
  redis:
    container_name: ledger-redis
    image: redis:latest
    networks:
      - ledger
  eyeshade-worker:
    container_name: ledger-eyeshade-worker
    command: "npm run start-eyeshade-worker"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "MONGODB_URI=mongodb://mongo/eyeshade"
    depends_on:
      - mongo
      - redis
  eyeshade-web:
    container_name: ledger-eyeshade-web
    ports:
      - "3002:3002"
    command: "npm run start-eyeshade"
    extends:
      file: base.yml
      service: ledger
    environment:
      - "MONGODB_URI=mongodb://mongo/eyeshade"
    depends_on:
      - mongo
      - redis
  ledger-worker:
    container_name: ledger-worker
    command: "npm run start-ledger-worker"
    extends:
      file: base.yml
      service: ledger
    depends_on:
      - mongo
      - redis
  ledger-web:
    container_name: ledger-web
    ports:
      - "3001:3001"
    command: "npm run start-ledger"
    extends:
      file: base.yml
      service: ledger
    depends_on:
      - mongo
      - redis
